jobs:
  - job: CI

    variables:
      - template: ../variables/globals.yml

    pool:
      vmImage: '$(OSVmImage)'

    steps:
      - script: sudo xcode-select --switch /Applications/Xcode_$(XcodeVersion).app
        displayName: 'Use Xcode $(XcodeVersion)'

      - script: npm install
        displayName: "Build"

      - script: npm run test
        displayName: "Run Tests"

      - script: |
          npm install -g autorest
          npm run build-sdks
        displayName: Generate Select SDKs and build
