jobs:
  - job: CI

    pool:
      vmImage: 'macOS-10.15'

    steps:
      - script: sudo xcode-select --switch /Applications/Xcode_11.5.app
        displayName: 'Use Xcode 11.5'

      - script: npm install
        displayName: Build

      - script: npm run test
        displayName: Run Tests

      - script: |
          npm run coverage-push -- $(Build.Repository.Name) $(Build.SourceBranch) $(github-token) $(storage-coverage-user) $(storage-coverage-pass)
        workingDirectory: node_modules/@microsoft.azure/autorest.testserver
        condition: and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))
        displayName: "Upload Coverage Report"
