jobs:
  - job: CI

    pool:
      vmImage: 'macOS-10.15'

    steps:
      - script: sudo xcode-select --switch /Applications/Xcode_11.5.app
        displayName: 'Use Xcode 11.5'

      - script: npm install
        displayName: Build

      - script: npm run test
        displayName: Run Tests

      - script: npm run buildChat
        displayName: Generate Chat SDK and build
